language: php
php: 
  - 7.2

before_script:
- wget https://cs.sensiolabs.org/download/php-cs-fixer-v2.phar -O php-cs-fixer-v2
- chmod a+x php-cs-fixer-v2

script:
- ./php-cs-fixer-v2 fix src --rules=@Symfony --diff --dry-run -vvv